### ISSUE TITLE
No available pages if no cookies

### ISSUE THREAD

**Issue by izhukov1992** [izhukov1992/mealing#1]

**Comment by izhukov1992** [comment]
Workaround: use link /api/v1/auth/ to auth, cookies will be created.

**Comment by michalstepniewski** [comment]
the page is empty. both in the https://mealing.herokuapp.com/ and in development server started. Why this might be? How can I fix this?

Sincerely,

Michal

**Comment by izhukov1992** [comment]
The issue was that there are no bower_components/datatables/media/js/jquery.dataTables.min.js and bower_components/datatables/media/css/jquery.dataTables.min.css.
I missed 'datatables' in my bower.json.
Fixed in commit №82.
https://mealing.herokuapp.com/ is available now.
